base/urls.py
from django.urls import path
from . import views
from django.contrib.auth.views import LogoutView

app_name = 'base'
urlpatterns = [
    path('login/',views.CustomLoginView.as_view(),name='login'),
    path('logout/',LogoutView.as_view(next_page='base:login'),name='logout'),
    path('register/',views.RegisterFormView.as_view(),name='register'),

    path('',views.TaskListView.as_view(),name='task-list'),
    path('task-detail/<int:pk>/',views.TaskDetailView.as_view(),name='task-detail'),
    path('create-task/',views.TaskCreateView.as_view(),name='create-task'),
    path('update-task/<int:pk>/',views.TaskUpdateView.as_view(),name='update-task'),
    path('delete-task/<int:pk>/',views.TaskDeleteView.as_view(),name='delete-task'),
]

todo/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('base.urls')),
]

base/models.py
from django.db import models
from django.contrib.auth.models import User

class Task(models.Model):
    user = models.ForeignKey(User,on_delete=models.CASCADE,null=True,blank=True)
    title = models.CharField(max_length=255)
    description = models.TextField(null=True,blank=True)
    complete = models.BooleanField(default=False)
    created_date = models.DateTimeField(auto_now_add=True)


    def __str__(self):
        return self.title   
    

    class Meta:
        ordering = ['complete']

base/forms.py
from django import forms
from .models import Task

class TaskForm(forms.ModelForm):
    class Meta:
        model = Task
        fields = ['title','description','complete']

base/views.py
from django.shortcuts import redirect
from django.views.generic import ListView,DeleteView,UpdateView,DetailView,CreateView,FormView
from .models import Task
from django.urls import reverse_lazy
from .forms import TaskForm
from django.contrib.auth.views import LoginView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import login


class CustomLoginView(LoginView):
    template_name = 'base/login.html'
    fields = '__all__'
    # if user is authenticated , they shouldn't be allowed on this page
    redirect_authenticated_user = True
    def get_success_url(self):
        return reverse_lazy('base:task-list')


class RegisterFormView(FormView):
    template_name = 'base/register.html'
    form_class = UserCreationForm
    redirect_authenticated_user = True
    success_url = reverse_lazy('base:task-list')

    def form_valid(self, form):
        user = form.save()
        if user is not None:
            login(self.request, user)
        return super().form_valid(form)

    def get(self, *args, **kwargs):
        if self.request.user.is_authenticated:
            return redirect('base:task-list')
        return super().get(*args, **kwargs)

class TaskListView(LoginRequiredMixin, ListView):
    model = Task
    context_object_name = 'tasks'
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['tasks'] = context['tasks'].filter(user=self.request.user)
        context['count'] = context['tasks'].filter(complete=False).count()
        search_input = self.request.GET.get('search-area') or ''
        if search_input:
            context['tasks'] = context['tasks'].filter(title__icontains=search_input)
        return context

class TaskDetailView(LoginRequiredMixin, DetailView):
    model = Task
    context_object_name = 'task'

class TaskCreateView(LoginRequiredMixin, CreateView):
    model = Task
    form_class = TaskForm
    success_url = reverse_lazy('base:task-list')
    def form_valid(self, form):
        form.instance.user = self.request.user
        return super().form_valid(form)
    

class TaskUpdateView(LoginRequiredMixin, UpdateView):
    model = Task
    fields = ['title','description','complete']
    success_url = reverse_lazy('base:task-list')

class TaskDeleteView(LoginRequiredMixin, DeleteView):
    model = Task
    success_url = reverse_lazy('base:task-list')

templates/base/login.html
{% extends 'main.html' %}
{% block content %}

<div class="header-bar">
    <h1>Login</h1>
</div>

<div class="card-body">
    <form method="post">
        {% csrf_token %}
        {{form.as_p}}
        <input class="button" type="submit" value="Login">
    </form>
    <p>don't have an account?<a href="{% url 'base:register' %}"> Register</a></p>
</div>
    

{% endblock %}

templates/base/register.html
{% extends 'main.html' %}
{% block content %}

<div class="header-bar">
    <h1>Register</h1>
</div>
<div class="card-body">
    <form method="post">
        {% csrf_token %}

        <label>{{form.username.label}}</label>
        {{form.username}}

        <label>{{form.password1.label}}</label>
        {{form.password1}}

        <label>{{form.password2.label}}</label>
        {{form.password2}}

        <input style="margin-top: 10px;" class="button" type="submit" value="Register">
    </form>
    <p>you already have an account?<a href="{% url 'base:login' %}"> Login</a></p>
</div>


{% endblock %}

templates/base/task_confirm_delete.html
{% extends 'main.html' %}
{% block content %}

    <div class="header-bar">
        <a href="{% url 'base:task-list' %}">&#8592; Go Back</a>
    </div>

    <div class="card-body">
        <form method="post">{% csrf_token %}
            <p>Are you sure you want to delete "{{ object }}"?</p>
            {{ form }}
            <input class="button" type="submit" value="Confirm">
        </form>
    </div>
    
{% endblock%}

templates/base/task_detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    {{task.user}} {{task.description}} {{task.created_date}}
</body>
</html>

templates/base/task_form.html
{% extends 'main.html' %}
{% block content %}

    <div class="header-bar">
        <a href="{% url 'base:task-list' %}">&#8592; Back</a>
    </div>


<div class="card-body">
    <form method="post">{% csrf_token %}
        {{ form.as_p }}
        <input class="button" type="submit" value="Submit">
    </form>
</div>
    
{% endblock %}

templates/base/task_list.html
{% extends 'main.html' %}
{% block content %}


<div class="header-bar">
    <div>
        <h1>Hello {{request.user|title}}</h1>
        <h3 style="margin:0">You have <i>{{count}}</i> incomplete task{{ count|pluralize:"s" }}</h3>
    </div>
    {% if request.user.is_authenticated %}
    <a href="{% url 'base:logout' %}">Logout</a>
    {% else %}
    <a href="{% url 'base:login' %}">Login</a>
    {% endif %}
</div>    

<div id="search-add-wrapper">
    <form method="get" style="margin-top: 20px;display: flex;">
        <input type="text" name="search-area">
        <input class="button" type="submit" value="Search">
    </form>
    <a id="add-link" href="{% url 'base:create-task' %}">&#x2b;</a>
</div>



<!-- <h1>TODO LIST</h1>
<hr>
<h3>Create Task</h3> -->



<div class="task-items-wrapper">
    {% for task in tasks %}
    <div class="task-wrapper">
        {% if task.complete %}
            <div class="task-title">
                <div class="task-complete-icon"></div>
                <i><s><a href="{% url 'base:update-task' pk=task.id %}">{{task}}</a></s></i>
            </div>
            <a class="delete-link" href="{% url 'base:delete-task' pk=task.id %}">&#215;</a>
        {% else %}
            <div class="task-title">
                <div class="task-incomplete-icon"></div>
                <a href="{% url 'base:update-task' pk=task.id %}">{{task}}</a>
            </div>
            <a class="delete-link" href="{% url 'base:delete-task' pk=task.id %}">&#215;</a>
        {% endif %}  
        

    </div>
    {% empty %}
        <h3>No Items in list</h3>
    {% endfor %}
</div>

<!-- <table>
    {% for task in tasks %}
    <tr>
        <th>Item</th>
        <th></th>
    </tr>
    
    <tr>
        <th>{{task.title}}</th>
        
        <th><a href="{% url 'base:update-task' pk=task.id %}">Update</a></th>
        <th><a href="{% url 'base:delete-task' pk=task.id %}">Delete</a></th>
    </tr>
    {% empty %}
        <h3>No Items in list</h3>
    {% endfor %}
</table> -->

{% endblock %}

templates/base/task_update.html
{% extends 'main.html' %}
{% block content %}
    <form method="post">{% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Update">
    </form>
{% endblock %}

templates/main.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>TO DO ITEMS</title>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Nunito:wght@200&display=swap" rel="stylesheet">
    <style>
        body{
            background-color: #FAFAFA;
            font-family: 'Nunito', sans-serif;
            padding-top: 50px;
        }

        h1,
        h2,
        h3,
        h4,
        h5,
        h6
            {
            font-family: 'Raleway', sans-serif;
        }

        a,
        p {
            color: #4b5156
        }

        a {
            font-weight: 600;
        }

        .container {
            max-width: 550px;
            margin: auto;
            background-color: #fff;
            -webkit-box-shadow: 2px 2px 13px -4px rgba(0, 0, 0, 0.21);
            box-shadow: 2px 2px 13px -4px rgba(0, 0, 0, 0.21);
        }

        input {
            outline: none;
            border: none;
        }

        .header-bar {
            display: flex;
            justify-content: space-between;
            color: #fff;
            padding: 10px;
            border-radius: 5px 5px 0 0;
            background: linear-gradient(90deg, #EEA390 0%, #EB796F 43%, #EB796F 100%);
        }

        .header-bar a {
            color: rgb(247, 247, 247);
            text-decoration: none;
        }

        .task-wrapper {
            display: flex;
            align-items: center;
            justify-content: space-between;
            background-color: #fff;
            border-top: 1px solid #dfe4ea;
            overflow: hidden;
        }

        .task-title {
            display: flex;
            padding: 20px;
        }

        .task-title a {
            text-decoration: none;
            color: #4b5156;
            margin-left: 10px;
        }

        .task-complete-icon {
            height: 20px;
            width: 20px;
            background-color: rgb(105, 192, 105);
            border-radius: 50%;
        }

        .task-incomplete-icon {
            height: 20px;
            width: 20px;
            background-color: rgb(218, 218, 218);
            border-radius: 50%;
        }

        .delete-link {
            text-decoration: none;
            font-weight: 900;
            color: #cf4949;
            font-size: 22px;
            line-height: 0;
            padding: 20px 0px;
        }

        .handle {
            display: inline-block;
            padding: 20px 16px;
            cursor: grab;
            user-select: none;
        }

        .handle:after,
        .handle:before {
            display: block;
            content: "";
        }

        .handle:active,
        .handle:active:before,
        .handle:active:after {
            cursor: grabbing;
        }

        .dropArea {
            background-color: #f1f2f6;
            color: black;
            border: #ced6e0 1px solid;
        }

        .selectedTask {
            opacity: 0.6;
        }


        #add-link {
            color: #EB796F;
            text-decoration: none;
            font-size: 42px;
            text-shadow: 1px 1px #81413b;
        }

        #search-add-wrapper {
            display: flex;
            justify-content: space-between;
            align-items: center;
            padding: 20px;
        }

        @media screen and (max-width:320px) {
            #search-add-wrapper {
                padding: 10px;
            }
        }

        input[type=text],
        input[type=password],
        textarea {
            border: 1px solid #757575;
            border-radius: 5px;
            padding: 10px;
            width: 90%;
        }

        label {
            padding-top: 10px !important;
            display: block;
        }

        ::placeholder {
            font-weight: 300;
            opacity: 0.5;
        }

        .button {
            border: 1px solid #757575;
            background-color: #FFF;
            color: #EB796F;
            padding: 10px;
            font-size: 14px;
            border-radius: 5px;
            cursor: pointer;
            text-decoration: none;
        }

        .card-body {
            padding: 20px;
        }

    </style>
</head>

<body>
    <div class="container">
        {% block content %}

        {% endblock %}
    </div>
</body>
</html>